services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'temp'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  dock:
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql